package net.maxgigapop.versans.nps.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-11-04T14:04:17.863-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://maxgigapop.net/versans/nps/api/", name = "NPServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface NPServicePortType {

    @RequestWrapper(localName = "setup", targetNamespace = "http://maxgigapop.net/versans/nps/api/", className = "net.maxgigapop.versans.nps.api.SetupContent")
    @WebMethod(action = "setup")
    @ResponseWrapper(localName = "setupResponse", targetNamespace = "http://maxgigapop.net/versans/nps/api/", className = "net.maxgigapop.versans.nps.api.SetupResponseContent")
    public void setup(
        @WebParam(mode = WebParam.Mode.INOUT, name = "transactionId", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        javax.xml.ws.Holder<java.lang.String> transactionId,
        @WebParam(name = "description", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        java.lang.String description,
        @WebParam(name = "serviceContract", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        net.maxgigapop.versans.nps.api.ServiceContract serviceContract,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        javax.xml.ws.Holder<java.lang.String> status,
        @WebParam(mode = WebParam.Mode.OUT, name = "message", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        javax.xml.ws.Holder<java.lang.String> message
    ) throws ServiceException;

    @RequestWrapper(localName = "teardown", targetNamespace = "http://maxgigapop.net/versans/nps/api/", className = "net.maxgigapop.versans.nps.api.TeardownContent")
    @WebMethod(action = "teardown")
    @ResponseWrapper(localName = "teardownResponse", targetNamespace = "http://maxgigapop.net/versans/nps/api/", className = "net.maxgigapop.versans.nps.api.TeardownResponseContent")
    public void teardown(
        @WebParam(mode = WebParam.Mode.INOUT, name = "transactionId", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        javax.xml.ws.Holder<java.lang.String> transactionId,
        @WebParam(name = "contractId", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        java.lang.String contractId,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        javax.xml.ws.Holder<java.lang.String> status,
        @WebParam(mode = WebParam.Mode.OUT, name = "message", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        javax.xml.ws.Holder<java.lang.String> message
    ) throws ServiceException;

    @RequestWrapper(localName = "query", targetNamespace = "http://maxgigapop.net/versans/nps/api/", className = "net.maxgigapop.versans.nps.api.QueryContent")
    @WebMethod(action = "query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://maxgigapop.net/versans/nps/api/", className = "net.maxgigapop.versans.nps.api.QueryResponseContent")
    public void query(
        @WebParam(mode = WebParam.Mode.INOUT, name = "transactionId", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        javax.xml.ws.Holder<java.lang.String> transactionId,
        @WebParam(name = "contractId", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        java.lang.String contractId,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        javax.xml.ws.Holder<java.lang.String> status,
        @WebParam(mode = WebParam.Mode.OUT, name = "message", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        javax.xml.ws.Holder<java.lang.String> message
    ) throws ServiceException;

    @RequestWrapper(localName = "modify", targetNamespace = "http://maxgigapop.net/versans/nps/api/", className = "net.maxgigapop.versans.nps.api.ModifyContent")
    @WebMethod(action = "mofidy")
    @ResponseWrapper(localName = "modifyResponse", targetNamespace = "http://maxgigapop.net/versans/nps/api/", className = "net.maxgigapop.versans.nps.api.ModifyResponseContent")
    public void modify(
        @WebParam(mode = WebParam.Mode.INOUT, name = "transactionId", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        javax.xml.ws.Holder<java.lang.String> transactionId,
        @WebParam(name = "description", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        java.lang.String description,
        @WebParam(name = "serviceContract", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        net.maxgigapop.versans.nps.api.ServiceContract serviceContract,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        javax.xml.ws.Holder<java.lang.String> status,
        @WebParam(mode = WebParam.Mode.OUT, name = "message", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
        javax.xml.ws.Holder<java.lang.String> message
    ) throws ServiceException;
}
