
package net.maxgigapop.versans.nps.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-11-17T15:09:22.247-05:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "serviceExceptionContent", targetNamespace = "http://maxgigapop.net/versans/nps/api/")
public class ServiceException extends Exception {
    
    private net.maxgigapop.versans.nps.api.ServiceExceptionContent serviceExceptionContent;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, net.maxgigapop.versans.nps.api.ServiceExceptionContent serviceExceptionContent) {
        super(message);
        this.serviceExceptionContent = serviceExceptionContent;
    }

    public ServiceException(String message, net.maxgigapop.versans.nps.api.ServiceExceptionContent serviceExceptionContent, Throwable cause) {
        super(message, cause);
        this.serviceExceptionContent = serviceExceptionContent;
    }

    public net.maxgigapop.versans.nps.api.ServiceExceptionContent getFaultInfo() {
        return this.serviceExceptionContent;
    }
}
